-- vim.loader.enable()

require "Juanfang.options"
require "Juanfang.keymaps"
require "Juanfang.plugins"
require "Juanfang.colorscheme"
require "Juanfang.lualine"
require "Juanfang.cmp"
require "Juanfang.lsp"
require "Juanfang.neo-tree"
require "Juanfang.telescope"
require "Juanfang.treesitter"
require "Juanfang.autopairs"
require "Juanfang.comment"
require "Juanfang.gitsigns"
require "Juanfang.barbar"
require "Juanfang.project"
require "Juanfang.which-key"
require "Juanfang.elixir"
-- require "Juanfang.java"
-- require "Juanfang.indent-line"
